repos:
  - repo: https://github.com/pre-commit/mirrors-ruff
    rev: v0.0.241
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy