name: QGIS Plugin CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QGIS environment
        run: |
          sudo apt update
          sudo apt install -y qgis python3-qgis python3-pyqt5 python3-pytest

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest test/