name: QGIS Plugin CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QGIS environment
        run: |
          sudo apt update
          sudo apt install -y qgis python3-qgis python3-pyqt5 python3-pytest

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=. --cov-report=html --cov-report=term-missing test/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/